### ISSUE TITLE
Monitoring pynab

### ISSUE THREAD

**Issue by AlanKK** [Murodese/pynab#117]
newznab-tmux has a nice monitor view that shows releases created and a lot of other info.  What is the best way to monitor pynab?

**Comment by brookesy2** [comment]
I just screen start.py. Shows releases being added etc. What is the other info, perhaps its something that could be added as a feature?

**Comment by AlanKK** [comment]
Something like this that shows some key metrics.  You can't see the column headers here but they are Parts, Binaries, Unprocessed Releases, Completed Releases.  The red and green numbers show changes +/- from the last interval.

![image](https://cloud.githubusercontent.com/assets/6281705/5693400/e9b70f06-98e8-11e4-895d-2a494fc3da93.png)

**Comment by brookesy2** [comment]
This is a bit beyond me to make! But perhaps someone else might be able to :)

**Comment by AlanKK** [comment]
I don't know the db schema.  If you can give me the queries for each of those four metrics, I can do it.

**Comment by brookesy2** [comment]
That sounds awesome. @Murodese knows the db a lot better than I do, so hopefully he can provide them!

**Comment by Murodese** [comment]
What's the difference between unprocessed/completed releases? Unprocessed is lacking some (or all) metadata?

Sounds like a good idea, I'm also looking at writing a byobu script or something to set up a monitor window similar to nn-tmux (but trying to avoid tmux, since I didn't have a great experience with that last time I used nn-tmux). If you're going to write a console script to show this info, put it in its own separate script in the root dir (monitor.py or some such) so that we can spin it off into a window pane when that's done.

Queries as below (take a look at the stuff in scripts/ for some idea of how to write a python cli script if you've never done it before):

```
from pynab.db import Part, Binary, Release, db_session

# parts
db.query(Part).count()

# binaries
db.query(Binary).count()

# unprocessed releases 
# as above, not sure what the criteria is. below is an example of whether they've been checked for pws or not
# which also involves downloading the rar, getting file info, determining release size, etc
# other postprocessing is nfo, sfv, tvrage, imdb - but it'd be difficult to show all that here
db.query(Release).filter(Release.passworded=='UNKNOWN').count()

# processed releases
db.query(Release).filter(Release.passworded!='UNKNOWN').count()
```

**Comment by Murodese** [comment]
You can actually already see some of this information, but it's in the webui (http://murodese.dyndns.org/ for an example). If you want any of that, the queries are in pynab/api.py:stats().

**Comment by Murodese** [comment]
Better yet, this looks nice: https://github.com/remiprev/teamocil

**Comment by AlanKK** [comment]
Thanks.  I'll take a look at those soon.  I am still ironing out some issues with my installation.

**Comment by Murodese** [comment]
Let me know if you're having issues.

**Comment by AlanKK** [comment]
Thanks.  I am OK for the moment.  I am converting from newznab-tmux, which didn't work at all for me.  Importing my nzb's is giving me a lot of "group doesn't exist" errors.  I am capturing the group names to add them and will then re-import the failed nzbs.

I may have a bug fix or two for you.  My import crashed a few times, which I fixed, and I couldn't read the colored logging to the console so I added a config to turn that off.  More later.

**Comment by Murodese** [comment]
No problem, chuck it all in a PR if you want. You can also speed things up by just adding the group if it doesn't exist. Change lines 231/232 in pynab/nzbs.py to:

```
if not group:
    group = Group(name=release['group_name'])
    db.add(group)
```

**Comment by Murodese** [comment]
The new monitoring stuff is in the anustart branch, with documentation. If you want to test it, it'd be appreciated. Just `git checkout anustart` and `python3 pynab.py update`. You might need to run `pip3 install -r requirements.txt` before the update, though.

Then start it however you like (there's a new upstart script or you can use `python3 pynab.py start` and then just `./monitor.sh` to start the monitor. Requires tmux and teamocil (which I just remembered I forgot to add to the install instructions).

**Comment by Murodese** [comment]
There's some documentation. Keep in mind the layout I provided is incredibly basic - check the teamocil docs and the sample layout in `teamocil/` and it should be easy enough to add your own :)

**Comment by Murodese** [comment]
This is now in the main branch.

**Comment by AlanKK** [comment]
I wrote the script that tracks parts, binaries and releases.  I left out unprocessed releases since it isn't good yet.  It seems to work well.  How would you like me to integrate it?  I could write to a log like you are doing with the other output and then display it with teamocil or just run the script from teamocil. 

I can also put in in pynab.py for a cli interface.

**Comment by Murodese** [comment]
If it's in a separate script, that's fine - you can just tell teamocil to open it in a new pane directly.

**Comment by Murodese** [comment]
You'll want to add a new teamocil config to include this, though - maybe based off this example :https://github.com/remiprev/teamocil#simple-three-pane-window.

**Comment by AlanKK** [comment]
There is a lot of wasted space using teamocil's layouts.  My stats windows only needs to be about 65 chars wide.  teamocil seems to only offer a few canned layouts with no fine grained control. The ruby environment is a pain too.  The layout I had in mind is like this:
|----------------------------
|   s    |                          |
|   t     |     log tail           |
|   a    |  -----------------  |
|   t     |                          |
|   s    |   log tail             |
|         |                          |
------------------------------
If I added a query that showed releases that haven't been post-processed, it would use a full 80 char width.  I look at that for a while and realized I don't have a good enough understanding of the database and how the data is processed.

**Comment by AlanKK** [comment]
I'll check in and do a pull request so you can see what I have so far.

**Comment by Murodese** [comment]
If you can find another layout manager that works decently, feel free to use it. I was avoiding tmux because it can be a pain and the layouts are complex as fuck, but you might have better luck.

It depends on what you consider to be a processed release, I guess. You'd have to break it down by category (since there's like 6-7 postproc functions and some operate on diff categories):

TV: finished if tvrage info added and file/password checking has been completed
Movie: finished if imdb info added and file/password checking has been completed
Everything else: finished if file/password checking has been completed

I can write a query to do something like that, if you want.

**Comment by AlanKK** [comment]
I know what you mean about tmux.  pita.  Give the stats.py a try and let me know what you think.  With newznab and nn-tmux, I thought it was important to see how parts, binaries and postprocessing releases were flowing so I could balance my system.  For example, backfilling can insert tens of millions of parts that can take days to process into binaries and releases.  

If you think monitoring the post processing backlog would be interesting to watch, send me a query and I'll add it to the script.

**Comment by Murodese** [comment]
Yeah, no worries. I'll check it out tonight.

pynab's a buttload faster at processing binaries/releases than nn, so that's a bit less of an issue. There are also forced stops during both update and backfill that prevent the segments table from getting too large (see config->scan), but I'm always a sucker for nice dataviz and it's something I always wanted to do but never really found time for.

Post-proc display might be nice, but it's not that big an issue, either - unlike nn, pynab post-processes releases newest to oldest per iteration, so new releases are never being missed. It's just really old releases that tend to take a while to be post-procced (incidentally, they're also the ones likely to fail post-proc).

Maybe we could do something like:

```
s | p | 
t  | o |   scanlog
a | s | ------------
t  | t  |   pplog
s | p |
```

**Comment by Murodese** [comment]
Curse you, whitespace formatting >: (

You get the idea.

**Comment by AlanKK** [comment]
Here's what my display looks like now.  I found a project called byobu, http://byobu.co/,  that looks nice.  It works with screen and tmux, is an easy install and seems very easy to use.  I still have more to learn about it before knowing if it will be good.

![image](https://cloud.githubusercontent.com/assets/6281705/5811823/e4163baa-a02a-11e4-8067-9480b9e8990e.png)

Notice I have been playing with log formatting too.  The upper log, postprocessing, is much compressed and cleaner than before.  More on that later.

I have only been running pynab for a few days but I can tell it is much faster than nn.  I would like to significantly step up my rate of backfilling.  I think that will give me a need to monitor/balance.  I also just like to see how the system is operating as it runs.

**Comment by Murodese** [comment]
Looks good. Feel free to do whatever you want to the logs - I cleaned them up a while ago (6 months?) but they've gotten a bit bloaty since. Maybe keep log.info for monitor output and debug information in log.debug (crazy, right?).

**Comment by Murodese** [comment]
Did you want to close the current PR and resubmit the one using byobu when it's done?
