### ISSUE TITLE
Daemon Logging Question

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#126]
Any idea why the daemon adds a dir in /var/log? /var/log/pynab/_pynab /var/log/pynab/_scan and _postprocess?

Also it seems to be ignoring my logging settings and never actually making any logs.

Also https://github.com/Murodese/pynab/blob/development-postgres/teamocil/standard.yml still refers to /var/www should it be updated to /opt/?

**Comment by Murodese** [comment]
The upstart script adds a dir in /var/log, since that's the default logging location for ubuntu installs. There's no way to easily link that to the python config file, though. Might be better to move that to the application itself, I guess.

What's your current logging_file value? If you set it to `/var/log/pynab/pynab.log` it'll create files like `/var/log/pynab/pynab_scan.log` and the like.

Lastly, doesn't really matter (it doesn't do anything), but I'll amend it.

**Comment by brookesy2** [comment]
No biggie. Was just curious really :)

I wasn't using .log, is it specifically checked? Guessing it needs an extension though?

Ahh, odd, as the tail statements bring up just errors if you run monitor.sh.

**Comment by Murodese** [comment]
Your personal user might not have permissions to read those files if the logs are being written by www-data? Just try `sudo ./monitor.sh`.

Added some changes to make it a bit more clear.

**Comment by brookesy2** [comment]
Naa, was using sudo. It will just be because the logs weren't created as I thought and I was distracted by these _dirs :)

Thanks again for the speedy responses. Will close this out!
