### ISSUE TITLE
SQL error after update

### ISSUE THREAD

**Issue by ajoergensen** [Murodese/pynab#134]
I did a pull and now this (in postprocess.py)

```sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column releases.pre_id does not exist
LINE 1: ...k_id, releases.episode_id AS releases_episode_id, releases.p...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "postprocess.py", line 43, in process_sfvs
    return pynab.sfvs.process(500)
  File "/opt/pynab/pynab/sfvs.py", line 47, in process
    for release in releases:
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column releases.pre_id does not exist
LINE 1: ...k_id, releases.episode_id AS releases_episode_id, releases.p...
                                                             ^
 'SELECT releases.id AS releases_id, releases.added AS releases_added, releases.posted AS releases_posted, releases.name AS releases_name, releases.search_name AS releases_search_name, releases.posted_by AS releases_posted_by, releases.status AS releases_status, releases.grabs AS releases_grabs, releases.size AS releases_size, releases.passworded AS releases_passworded, releases.unwanted AS releases_unwanted, releases.group_id AS releases_group_id, releases.category_id AS releases_category_id, releases.regex_id AS releases_regex_id, releases.tvshow_id AS releases_tvshow_id, releases.tvshow_metablack_id AS releases_tvshow_metablack_id, releases.movie_id AS releases_movie_id, releases.movie_metablack_id AS releases_movie_metablack_id, releases.nzb_id AS releases_nzb_id, releases.rar_metablack_id AS releases_rar_metablack_id, releases.nfo_id AS releases_nfo_id, releases.nfo_metablack_id AS releases_nfo_metablack_id, releases.sfv_id AS releases_sfv_id, releases.sfv_metablack_id AS releases_sfv_metablack_id, releases.episode_id AS releases_episode_id, releases.pre_id AS releases_pre_id \nFROM releases JOIN groups ON groups.id = releases.group_id JOIN nzbs ON nzbs.id = releases.nzb_id \nWHERE releases.sfv_id IS NULL AND releases.sfv_metablack_id IS NULL ORDER BY releases.posted DESC \n LIMIT %(param_1)s' {'param_1': 500}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "postprocess.py", line 224, in <module>
    main()
  File "postprocess.py", line 123, in main
    data = t.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "postprocess.py", line 46, in process_sfvs
    raise Exception
Exception
```

**Comment by brookesy2** [comment]
This is actually due to a dodgy pull request by me :(

This pull request fixes it:

https://github.com/Murodese/pynab/pull/133

**Comment by ajoergensen** [comment]
I am by no means fluent in git - Is it possible to manually merge the PR into my local repo until it's merged here?

**Comment by brookesy2** [comment]
It would be the blind leading the blind im afraid! You could add my repo as a remote and merge from that, but probably not worth it.

I think it might also work if you just copy:

https://github.com/brookesy2/pynab/blob/development-postgres/alembic/versions/24a0bbbf5a1_add_pre_columns.py

Then in the pynab dir do:

alembic upgrade head

Make sure you backup your dir before doing this :)

**Comment by brookesy2** [comment]
I am just testing this now so as not to lead you astray.

**Comment by brookesy2** [comment]
Ok this is really weird. I made a brand new install and all the tables/columns were created correctly. So it seems there is some oddity in the upgrade path in alembic.

Might need @Murodese to take a look as it seems the new install works correctly.

Here is an updated alembic file with all the fields, but it may conk out due to duplicated fields.

https://github.com/brookesy2/pynab/blob/8991dadc022ea3cb447c9e3c5d3752430ad9b753/alembic/versions/1de31e1a78b_add_pre_columns.py

**Comment by Murodese** [comment]
You can test a PR by doing `git fetch` and then `git checkout pr/<number of pull request>`, e.g. `git checkout pr/133`. Once it's merged into the main branch, you can then go back by just doing `git checkout development-postgres`.

I'll grab that alembic upgrade and integrate it directly into the stream.

**Comment by Murodese** [comment]
Ok, here's what you'll want to do:

    > git pull
    > alembic downgrade c5c72142b8
    > alembic upgrade head

That should fix it, let me know if it doesn't.

**Comment by Murodese** [comment]
Alembic versioning can be a bit of a minefield as a developer, but it works pretty well once you get it down. It's important to remember that alembic's taking changes off your database directly, so if you add new columns or indexes or change the model after already running `alembic upgrade head`, you either need to downgrade to the previous revision, delete the revision you had previously creating stuff and autogenerate a new one, or just generate new ones to keep the flow going. The idea is that you always need to keep the db in a clean state, so upgrade/downgrade work properly. 

As an example, the upgrade/downgrade in revision 3821d174074 created/dropped unique constraints that didn't have a name. Alembic would've autogenerated that, but they need to be named (because you can't tell alembic to drop an unnamed key). Postgres gives it a name, but it changes a bit between versions so it's unreliable. Anytime you create a revision, just check over it to make sure there's nothing obviously missing :) There are examples of all sorts of stuff that I've been doing in the revisions themselves, from the simple (269915fe13c_add_hash_to_binary.py) to the complex (27124764226_fix_nzbs_broken_in_commit_8b9bce0.py).

I might bring back the master branch just so we leave the dev branch to be an unstable playground, and people that don't want to have to deal with our messes can stick with master. I'll do that tonight.

**Comment by brookesy2** [comment]
@Murodese Thanks for the detailed explanations, much appreciated. I think the downgrade bit is the best tip, I will remember to do that next time if I have additional stuff to add.

One thing, it seems to conk out when it notices its duplicating work, say the field already exists and it is trying again, is there any way to make it fail gracefully? I guess this relates to the clean slate you explained, probably shouldn't get yourself into this situation :)

We can call the new branch, the brookesy2 messup branch :p

**Comment by Murodese** [comment]
No, it's not supposed to fail gracefully :) Much like any version control system, you should be able to take a revision at any point and have it apply every single diff successfully. Good example: I just merged the development-postgre and master branches successfully, even though they're about a year apart.

Everything in upgrade/downgrade should operate on the assumption that the DB is in the state that it was for the previous revision. There are some exceptions to that, notably when dealing with data - the stuff in `27124764226_fix_nzbs_broken_in_commit_8b9bce0.py` has no downgrade, for instance, because it doesn't affect table structure (and it does already check to ensure it's only changing affected data).

Any column upgrades or tables etc should have an appropriate downgrade, though you can speed some up - if you're dropping a whole table, you can just leave it at that as any associated indexes and keys will be dropped with it.

The new dev branch is the same as the old one (`development-postgre`), it's just that the `master` branch is now up-to-date for stable releases.

**Comment by brookesy2** [comment]
That makes sense! Again thank you for the detailed explanations, very helpful!

I upgraded my main install with the updates for this issue and everything is running fine, so hopefully we can close this one out.

Thank you!!

**Comment by ajoergensen** [comment]
Fixed my problems as well, thanks.
