### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by AlanKK** [Murodese/pynab#136]
Here's my proposal for improving logging.

1.  Replace logging_file with logging_dir in config.py

2.  Condense the format so most log msgs fit in a smaller window.

3.  Move most of the normal errors to debug.

4.  Change the file names from pynab_*.log to *.log.  So pynab_backfill.log becomes backfill.log.  It is just easier to use filename completion when they start with different letters.

**Comment by Murodese** [comment]
1 and 4 already happened, barring backfill. Backfill's a slightly tricky case, because the log name is derived from the calling script (which for both update and backfill is scan.py). An easy fix to this is to require any module loading logging to initialise with a variable indicating which file it should go into, ie.

```
from pynab import log_init, log
...
if backfill:
    log_init('backfill')
else:
    log_init('update')
```

No issues with 3, either - keep info for stuff meant to be displayed, debug for debugging and all exceptions/fatal errors to error.

**Comment by AlanKK** [comment]
Sounds good.  Do you have the changes for 1 and 4 checked in?  I'll change stats.py to work with that too.  

Also, should I be working off master or development-postres?

**Comment by Murodese** [comment]
`development-postgres` from now on, I'll periodically merge them. `master` stays as the stable branch.

That stuff was in 483ea1ec33c94fcad691052fcbe642c6aaa0fa3f and a couple followups. The `log_init` stuff I just thought of, so that's not in there.

**Comment by Murodese** [comment]
Stuff now logs into whatever name `log_init()` is given. If it's not called, it uses the calling script (how it was before). So backfill stuff now goes into backfill.log, updates into update.log, api into api.log, etc.
