### ISSUE TITLE
Get CouchPotato working with Pynab?

### ISSUE THREAD

**Issue by boo1234** [Murodese/pynab#210]
The conversation leading up to this comment is the issue: https://github.com/RuudBurger/CouchPotatoServer/issues/5067#issuecomment-121111075

Sorry to repost it here, but I did think that this was a better spot for changes related to pynab vs another project. :)

**Comment by Murodese** [comment]
Yup, good reminder. I'll check this out now.

**Comment by Murodese** [comment]
Ah, good news. CP supports adding extra tags so it's a trivial change. I'll do it now.

**Comment by boo1234** [comment]
Is this on the development-postgres (which I'm using)? For that matter, what's the difference between master and development-postgres?

**Comment by Murodese** [comment]
Actually, CP doesn't pass those extra tags on during the nzb download, just the search, so I'll need to think of another way.

It'll be on `development-postgres`. The difference at the moment isn't much, because they got synced recently. The dev branch is used for experimental changes and generally all new work until they get merged, which happens every few months.

**Comment by Murodese** [comment]
Try that :)

**Comment by boo1234** [comment]
Magic. Well done, sir.
